import type { Course } from "@/lib/content/types";

export const AIRFORCE_COURSES: Course[] = [
  {
    slug: "gd-pilot",
    name: "General Duty Pilot (GD Pilot)",
    tagline: "The most competitive flying commission in Pakistan: fighter and transport pilots.",
    description:
      "The General Duty Pilot course commissions officers into the flying branch of the Pakistan Air Force. Cadets train at the PAF Academy Risalpur and the College of Aeronautical Engineering, learning to fly multi-engine and fighter aircraft including the JF-17 and F-16. Selection includes a Pilot Aptitude Test after ISSB.",
    icon: "plane",
    level: "Officer",
    commission: "Regular Commission",
    eligibility: [
      "Pakistani citizens, male and female candidates as per the advertisement; unmarried at the time of joining.",
      "Age 16 to 22 years on the advertised cut-off date.",
      "FSc Pre-Engineering, Pre-Medical or Computer Science with at least 60 to 65% aggregate, or A-Level with Physics and Maths or Biology.",
      "Minimum height 5 ft 4 in for male candidates (about 4 ft 10 in where female standards apply).",
      "Vision 6/6 each eye without glasses for GD Pilot, plus flying aptitude.",
    ],
    gender: "Male and female candidates",
    audience: "both",
    ageLimit: "16 – 22 years",
    education:
      "FSc Pre-Engineering / Pre-Medical / Computer Science or A-Level with Physics plus Maths or Biology, at the aggregate stated in the advertisement.",
    physical:
      "Height 5 ft 4 in minimum for male candidates · 6/6 uncorrected vision each eye · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Married candidates at the time of joining.",
      "Anyone who has passed the 22nd birthday at the initial test.",
      "Candidates who do not meet the 6/6 uncorrected vision standard.",
      "Anyone who fails the Pilot Aptitude Test or the medical board.",
    ],
    benefits: [
      "Permanent Commission in the PAF flying branch.",
      "Fully funded four-year training at the PAF Academy and the College of Aeronautical Engineering.",
      "Flying the JF-17, F-16 and transport fleet, with flying allowance on top of salary.",
      "Officer rank, pension, base housing and children's education allowance.",
    ],
    steps: [
      "Register online at joinpaf.gov.pk and choose your test date and centre.",
      "Clear the initial written test: English, maths, physics, chemistry, general knowledge and intelligence.",
      "Pass the preliminary medical and physical screening.",
      "Clear the four-day ISSB assessment at Gujranwala.",
      "Pass the Pilot Aptitude Test and the final medical board.",
      "Join the PAF Academy Risalpur for four years of training.",
    ],
    duration: "4 years of flying and officer training",
    fee: "Free (fully government-funded)",
    documents: [
      "CNIC / B-Form and NADRA smart cards",
      "Matric and FSc / A-Level certificates with DMC",
      "Equivalence certificate for A-Level candidates",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaf.gov.pk",
    summary:
      "Aged 16 to 22, unmarried, 6/6 eyesight, at least 5 ft 4 in? Flying aptitude and the medical board decide this one, so start fitness and eyesight work early.",
  },
  {
    slug: "aeronautical-engineering",
    name: "Aeronautical Engineering (CAE)",
    tagline: "Aero engineering officers: aircraft, avionics aur propulsion.",
    description:
      "The Aeronautical Engineering course commissions officers who maintain the PAF's aircraft fleet. It is a four-year programme with a degree in aerospace engineering or avionics, covering aerodynamics, structures, propulsion, avionics and aircraft maintenance.",
    icon: "wrench",
    level: "Officer",
    commission: "Regular Commission",
    eligibility: [
      "Pakistani citizens; the course is advertised for male and female candidates in most intakes.",
      "Unmarried at the time of joining for the permanent commission course.",
      "Age 16 to 22 years on the advertised cut-off date.",
      "FSc Pre-Engineering with Physics, Chemistry and Mathematics, or equivalent A-Level, at the aggregate stated in the advertisement; DAE in relevant disciplines is also accepted in some intakes.",
      "Height 5 ft 4 in for male candidates, 4 ft 10 in for female candidates.",
    ],
    gender: "Male and female candidates",
    audience: "both",
    ageLimit: "16 – 22 years",
    education:
      "FSc Pre-Engineering or equivalent A-Level (Physics, Chemistry, Mathematics) at the advertised aggregate; DAE in avionics, electrical or mechanical in some intakes.",
    physical:
      "Height 5 ft 4 in for male candidates, 4 ft 10 in for female candidates · medically fit.",
    nationality: "Pakistan",
    notEligible: [
      "Married candidates for the permanent commission course.",
      "Candidates from non-technical subject combinations.",
      "Anyone failing the medical or physical efficiency test.",
    ],
    benefits: [
      "Permanent Commission in the PAF engineering branch.",
      "Four-year funded programme with a BE in Aerospace Engineering or Avionics.",
      "Hands-on work on the aircraft that keep the PAF flying.",
      "Officer career with allowances, pension and family benefits.",
    ],
    steps: [
      "Register online at joinpaf.gov.pk for the Aeronautical Engineering course.",
      "Clear the initial written test.",
      "Pass the preliminary medical and physical screening.",
      "Clear the ISSB assessment.",
      "Final medical board and interview at PAF recruitment.",
      "Join the College of Aeronautical Engineering for four years of training.",
    ],
    duration: "4 years at the College of Aeronautical Engineering",
    fee: "Free (fully government-funded)",
    documents: [
      "CNIC / B-Form and NADRA smart cards",
      "Matric and FSc / A-Level certificates with DMC",
      "Equivalence certificate for A-Level or DAE candidates",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaf.gov.pk",
    summary:
      "FSc Pre-Engineering with Physics, Chemistry and Maths, aged 16 to 22? The CAE course is the engineering flying-adjacent commission in the PAF.",
  },
  {
    slug: "air-defence",
    name: "Air Defence Course",
    tagline: "Radar, missiles aur air defence network ke liye officers.",
    description:
      "The Air Defence course commissions officers into the PAF's air defence branch, responsible for radars, surface-to-air missiles, command and control, and the protection of air bases and national airspace.",
    icon: "radio",
    level: "Officer",
    commission: "Regular Commission",
    eligibility: [
      "Pakistani male citizens, unmarried at the time of joining.",
      "Age 16 to 22 years on the advertised cut-off date.",
      "FSc with Physics and Mathematics, or an equivalent A-Level combination, at the advertised aggregate.",
      "Minimum height 5 ft 4 in.",
      "Medically and physically fit.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "16 – 22 years",
    education: "FSc with Physics and Mathematics, or equivalent A-Level, at the advertised aggregate.",
    physical:
      "Height 5 ft 4 in minimum · medically fit · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Married candidates.",
      "Candidates without Physics and Mathematics at the required level.",
      "Anyone outside the advertised age window or failing the medical board.",
    ],
    benefits: [
      "Permanent Commission in the PAF air defence branch.",
      "Operation of national air defence systems and radars.",
      "Four-year funded officer training with technical specialisation.",
      "Officer pay, allowances, housing and pension.",
    ],
    steps: [
      "Register online at joinpaf.gov.pk for the Air Defence course.",
      "Clear the initial written test.",
      "Pass the preliminary medical and physical screening.",
      "Clear the ISSB assessment.",
      "Final medical board and selection.",
      "Join for air defence officer training.",
    ],
    duration: "4 years of officer training",
    fee: "Free (government-funded)",
    documents: [
      "CNIC / B-Form and NADRA smart cards",
      "Matric and FSc / A-Level certificates with DMC",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaf.gov.pk",
    summary:
      "Male candidate with Physics and Maths in FSc, aged 16 to 22? The air defence course is a permanent-commission technical track.",
  },
  {
    slug: "admin-special-duties",
    name: "Admin & Special Duties",
    tagline: "Administration, logistics aur special duties officers.",
    description:
      "The Admin and Special Duties course commissions officers into the PAF's administrative and ground support establishment: base administration, personnel management, security, protocol and support functions that keep air bases running.",
    icon: "users",
    level: "Officer",
    commission: "Regular Commission",
    eligibility: [
      "Pakistani male citizens, unmarried at the time of joining.",
      "Age 16 to 22 years on the advertised cut-off date.",
      "FSc or graduation, or equivalent A-Level, at the aggregate stated in the advertisement.",
      "Minimum height 5 ft 4 in.",
      "Medically and physically fit.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "16 – 22 years",
    education: "FSc or graduation, or equivalent A-Level, as per the advertisement.",
    physical:
      "Height 5 ft 4 in minimum · medically fit · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Married candidates.",
      "Anyone outside the advertised age window.",
      "Anyone failing the medical or ISSB assessment.",
    ],
    benefits: [
      "Permanent Commission in the PAF administration and support branch.",
      "Four-year funded officer training with a degree component.",
      "Career in base administration, security and personnel management.",
      "Officer status with allowances, housing and pension.",
    ],
    steps: [
      "Register online at joinpaf.gov.pk for the Admin and Special Duties course.",
      "Clear the initial written test.",
      "Pass the preliminary medical and physical screening.",
      "Clear the ISSB assessment.",
      "Final medical board and selection.",
      "Join for officer training.",
    ],
    duration: "4 years of officer training",
    fee: "Free (government-funded)",
    documents: [
      "CNIC / B-Form and NADRA smart cards",
      "Matric, FSc and graduation certificates with DMC",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaf.gov.pk",
    summary:
      "FSc or graduate, aged 16 to 22? Admin and Special Duties is a permanent-commission route for ground and support officers.",
  },
  {
    slug: "logistics",
    name: "Logistics (PC)",
    tagline: "Supply chain, procurement aur stores ke liye officers.",
    description:
      "The Logistics permanent commission course commissions officers into the PAF's logistics chain: supply, procurement, inventory, warehousing and distribution across air bases and units. It suits candidates who are organised, methodical and interested in management rather than flying.",
    icon: "package",
    level: "Officer",
    commission: "Regular Commission",
    eligibility: [
      "Pakistani male citizens, unmarried at the time of joining.",
      "Age 16 to 22 years on the advertised cut-off date.",
      "FSc or equivalent A-Level at the aggregate stated in the advertisement.",
      "Minimum height 5 ft 4 in.",
      "Medically and physically fit.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "16 – 22 years",
    education: "FSc or equivalent A-Level at the advertised aggregate.",
    physical:
      "Height 5 ft 4 in minimum · medically fit · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Married candidates.",
      "Anyone outside the advertised age window.",
      "Anyone failing the medical or ISSB assessment.",
    ],
    benefits: [
      "Permanent Commission in the PAF logistics branch.",
      "Four-year funded officer training.",
      "Supply chain, procurement and stores management career.",
      "Officer pay, allowances, housing and pension.",
    ],
    steps: [
      "Register online at joinpaf.gov.pk for the Logistics course.",
      "Clear the initial written test.",
      "Pass the preliminary medical and physical screening.",
      "Clear the ISSB assessment.",
      "Final medical board and selection.",
      "Join for officer training.",
    ],
    duration: "4 years of officer training",
    fee: "Free (government-funded)",
    documents: [
      "CNIC / B-Form and NADRA smart cards",
      "Matric and FSc / A-Level certificates with DMC",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaf.gov.pk",
    summary:
      "Aged 16 to 22 with FSc? The Logistics permanent commission is a management and supply career inside the PAF.",
  },
  {
    slug: "engineering-ssc",
    name: "Engineering Branch (SSC)",
    tagline: "Graduate engineers ke liye short service commission.",
    description:
      "The PAF Engineering Branch short service commission recruits graduate engineers into officer service. Branch options have included chemical, aeronautical, electrical and civil engineering, with the selection focused on academic strength followed by ISSB and medical boards.",
    icon: "cpu",
    level: "Officer",
    commission: "Short Service Commission",
    eligibility: [
      "Pakistani male citizens.",
      "Age 20 to 26 years as per the advertisement.",
      "BE / BS Engineering in the advertised discipline from a PEC-recognised institution; post-graduates are preferred in some intakes.",
      "Minimum 60% marks or 2.5 out of 4 CGPA.",
      "Height 5 ft 4 in minimum; medically and physically fit.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "20 – 26 years",
    education: "BE / BS Engineering in the advertised discipline, at 60% or 2.5 CGPA minimum.",
    physical:
      "Height 5 ft 4 in minimum · medically fit · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Female candidates in the male engineering SSC advertisement.",
      "Engineers below the advertised marks or CGPA threshold.",
      "Anyone outside the 20 to 26 year window.",
    ],
    benefits: [
      "Officer commission with a short service commitment and extension options.",
      "Engineering career across aircraft, systems and infrastructure.",
      "About 24 weeks of structured officer and technical training.",
      "Officer pay, allowances, housing and pension.",
    ],
    steps: [
      "Register online at joinpaf.gov.pk for the Engineering Branch SSC.",
      "Clear the initial written and academic test.",
      "Pass the preliminary medical and physical screening.",
      "Clear the ISSB assessment.",
      "Final medical board and selection.",
      "Complete about 24 weeks of training and receive commission as a Flying Officer.",
    ],
    duration: "About 24 weeks of training",
    fee: "Free (government-funded)",
    documents: [
      "CNIC / B-Form and NADRA smart cards",
      "Matric, FSc and engineering transcripts with DMC",
      "PEC registration where applicable",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaf.gov.pk",
    summary:
      "Graduate engineer, aged 20 to 26, 60% or 2.5 CGPA? The Engineering Branch SSC commissions you as a Flying Officer after about six months of training.",
  },
  {
    slug: "education-ssc",
    name: "Education Branch (SSC)",
    tagline: "Teachers and academic specialists for PAF schools and institutions.",
    description:
      "The PAF Education Branch commissions post-graduates as officers to run PAF schools, colleges and training institutions. Subjects typically advertised include English, mathematics, physics, chemistry, computer science, pak studies, psychology and management sciences.",
    icon: "book-open",
    level: "Officer",
    commission: "Short Service Commission",
    eligibility: [
      "Pakistani male and female citizens, depending on the advertisement.",
      "Age 20 to 29 years as per the advertisement.",
      "MPhil, MS or MA in the advertised subject from an HEC-recognised university.",
      "Height 5 ft 4 in for male candidates; female standards where applicable.",
      "Medically and physically fit.",
    ],
    gender: "Male and female candidates",
    audience: "both",
    ageLimit: "20 – 29 years",
    education: "MPhil / MS / MA in the advertised subject from an HEC-recognised university.",
    physical:
      "Height 5 ft 4 in for male candidates · medically fit · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Anyone without a post-graduation in an advertised subject.",
      "Anyone outside the advertised age window.",
      "Anyone failing the medical or ISSB assessment.",
    ],
    benefits: [
      "Officer commission for educators, teaching in PAF institutions.",
      "A stable career with military benefits and pension.",
      "Rank of Flying Officer on commissioning.",
      "Housing, medical and children's education benefits.",
    ],
    steps: [
      "Register online at joinpaf.gov.pk for the Education Branch.",
      "Clear the initial written and academic test.",
      "Pass the preliminary medical and physical screening.",
      "Clear the ISSB assessment.",
      "Final medical board and selection.",
      "Complete training and receive commission as a Flying Officer.",
    ],
    duration: "About 24 weeks of training",
    fee: "Free (government-funded)",
    documents: [
      "CNIC / B-Form and NADRA smart cards",
      "Matric, graduation and post-graduation transcripts with DMC",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaf.gov.pk",
    summary:
      "Post-graduate in a teaching subject, aged 20 to 29? The Education Branch is a commissioned career teaching in PAF institutions.",
  },
  {
    slug: "accounts-ssc",
    name: "Accounts Branch (SSC)",
    tagline: "Accounts, audit aur financial management officers.",
    description:
      "The Accounts Branch short service commission recruits commerce and finance graduates into the PAF's financial management: accounting, audit, budgeting and financial control across air bases and headquarters.",
    icon: "scale",
    level: "Officer",
    commission: "Short Service Commission",
    eligibility: [
      "Pakistani male and female citizens, depending on the advertisement.",
      "Age 20 to 26 years as per the advertisement.",
      "BCom, BBA, MCom, MBA, ACCA, ACMA, or BS / MS in Finance, Accounting or Economics with at least 65% marks or 2.7 CGPA.",
      "Height 5 ft 4 in for male candidates.",
      "Medically and physically fit.",
    ],
    gender: "Male and female candidates",
    audience: "both",
    ageLimit: "20 – 26 years",
    education:
      "BCom / BBA / MCom / MBA / ACCA / ACMA or BS / MS in Finance or Accounting, at 65% or 2.7 CGPA minimum.",
    physical:
      "Height 5 ft 4 in for male candidates · medically fit · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Anyone below the advertised marks or CGPA threshold.",
      "Anyone outside the advertised age window.",
      "Anyone failing the medical or ISSB assessment.",
    ],
    benefits: [
      "Officer commission in financial management.",
      "Audit, accounting and budgeting career across PAF establishments.",
      "Rank of Flying Officer on commissioning.",
      "Military allowances, housing, medical and pension benefits.",
    ],
    steps: [
      "Register online at joinpaf.gov.pk for the Accounts Branch.",
      "Clear the initial written and academic test.",
      "Pass the preliminary medical and physical screening.",
      "Clear the ISSB assessment.",
      "Final medical board and selection.",
      "Complete training and receive commission as a Flying Officer.",
    ],
    duration: "About 24 weeks of training",
    fee: "Free (government-funded)",
    documents: [
      "CNIC / B-Form and NADRA smart cards",
      "Matric, FSc and commerce or finance transcripts with DMC",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaf.gov.pk",
    summary:
      "Commerce or finance graduate with 65% or 2.7 CGPA, aged 20 to 26? The Accounts Branch is the PAF's finance commission.",
  },
  {
    slug: "it-ssc",
    name: "IT Branch (SSC)",
    tagline: "Computer science aur IT professionals for PAF networks.",
    description:
      "The IT Branch short service commission recruits computer science and information technology graduates to run PAF networks, cyber operations, software and information systems. Cyber defence and secure communications are central to the role.",
    icon: "cpu",
    level: "Officer",
    commission: "Short Service Commission",
    eligibility: [
      "Pakistani male and female citizens, depending on the advertisement.",
      "Age 20 to 26 years as per the advertisement.",
      "BS / MS in Computer Science, Information Technology or a related discipline with at least 65% marks or the advertised CGPA.",
      "Height 5 ft 4 in for male candidates.",
      "Medically and physically fit.",
    ],
    gender: "Male and female candidates",
    audience: "both",
    ageLimit: "20 – 26 years",
    education:
      "BS / MS in Computer Science, Information Technology or related field, at the advertised marks or CGPA.",
    physical:
      "Height 5 ft 4 in for male candidates · medically fit · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Anyone without a recognised CS or IT degree.",
      "Anyone outside the advertised age window.",
      "Anyone failing the medical or ISSB assessment.",
    ],
    benefits: [
      "Officer commission in the PAF's IT and cyber establishment.",
      "Work on secure military networks, systems and cyber defence.",
      "Rank of Flying Officer on commissioning.",
      "Military allowances, housing, medical and pension benefits.",
    ],
    steps: [
      "Register online at joinpaf.gov.pk for the IT Branch.",
      "Clear the initial written and academic test.",
      "Pass the preliminary medical and physical screening.",
      "Clear the ISSB assessment.",
      "Final medical board and selection.",
      "Complete training and receive commission as a Flying Officer.",
    ],
    duration: "About 24 weeks of training",
    fee: "Free (government-funded)",
    documents: [
      "CNIC / B-Form and NADRA smart cards",
      "Matric, FSc and CS or IT transcripts with DMC",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaf.gov.pk",
    summary:
      "CS or IT graduate, aged 20 to 26? The IT Branch commissions you into PAF networks and cyber operations.",
  },
  {
    slug: "met-branch-ssc",
    name: "Met (Medical) Branch (SSC)",
    tagline: "MBBS doctors for PAF hospitals and air base medical units.",
    description:
      "The Met Branch short service commission commissions doctors into the PAF Medical Branch. They serve in PAF hospitals, air base medical units and flying medicine, with the same professional standards as the civil health service plus military medical training.",
    icon: "stethoscope",
    level: "Officer",
    commission: "Short Service Commission",
    eligibility: [
      "Pakistani citizens, male or female depending on the advertisement.",
      "MBBS from a PMDC-recognised medical college, registered with the Pakistan Medical and Dental Council.",
      "Age generally 20 to 30 years as per the advertisement.",
      "Height 5 ft 4 in for male candidates.",
      "Medically and physically fit on military standards.",
    ],
    gender: "Male and female candidates",
    audience: "both",
    ageLimit: "20 – 30 years",
    education: "MBBS with PMDC registration; specialist degrees preferred in some intakes.",
    physical:
      "Height 5 ft 4 in for male candidates · medically fit on military standards.",
    nationality: "Pakistan",
    notEligible: [
      "Doctors not registered with the Pakistan Medical and Dental Council.",
      "Anyone above the advertised age limit.",
      "Anyone failing the Armed Forces medical board.",
    ],
    benefits: [
      "Medical officer commission in the PAF.",
      "Clinical work in PAF hospitals and air base units, including aviation medicine.",
      "Officer pay, allowances, housing, medical care and pension.",
      "Postgraduate and specialist training support.",
    ],
    steps: [
      "Watch joinpaf.gov.pk for the Met Branch advertisement.",
      "Register online with PMDC details.",
      "Clear the initial written test and preliminary medical board.",
      "Pass the ISSB assessment and interview.",
      "Final medical board and grant of commission.",
    ],
    duration: "Initial medical orientation course, then posting",
    fee: "Free (government service)",
    documents: [
      "CNIC / B-Form and NADRA smart cards",
      "MBBS degree and PMDC registration certificate",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaf.gov.pk",
    summary:
      "MBBS with PMDC registration? The Met Branch is the PAF's medical commission, advertised periodically on joinpaf.gov.pk.",
  },
  {
    slug: "legal-branch-ssc",
    name: "Legal Branch (JAG)",
    tagline: "Law graduates for the Judge Advocate General's branch.",
    description:
      "The PAF Legal Branch commissions law graduates through the Judge Advocate General. Selected officers serve as legal advisers, conduct courts martial and handle service law, procurement and disciplinary matters across the force.",
    icon: "scale",
    level: "Officer",
    commission: "Short Service Commission",
    eligibility: [
      "Pakistani citizens, male or female depending on the advertisement.",
      "LLB from a recognised institution, registered with the Bar Council.",
      "Age generally 21 to 30 years as per the advertisement.",
      "Height 5 ft 4 in for male candidates.",
      "Medically and physically fit.",
    ],
    gender: "Male and female candidates",
    audience: "both",
    ageLimit: "21 – 30 years",
    education: "LLB with Bar Council registration; higher degrees preferred.",
    physical:
      "Height 5 ft 4 in for male candidates · medically fit · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Anyone not enrolled with the Bar Council.",
      "Anyone outside the advertised age window.",
      "Anyone failing the medical or ISSB assessment.",
    ],
    benefits: [
      "Officer commission as a legal adviser in the PAF.",
      "Courts martial, service law and disciplinary work.",
      "A dual career path: military law plus civilian legal practice.",
      "Officer pay, allowances, housing and pension.",
    ],
    steps: [
      "Watch joinpaf.gov.pk for the JAG Legal Branch advertisement.",
      "Register online with Bar Council details.",
      "Clear the initial written test and preliminary medical board.",
      "Pass the ISSB assessment and interview.",
      "Final medical board and grant of commission.",
    ],
    duration: "Initial legal officer training, then posting",
    fee: "Free (government service)",
    documents: [
      "CNIC / B-Form and NADRA smart cards",
      "LLB degree and Bar Council enrolment certificate",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaf.gov.pk",
    summary:
      "Law graduate enrolled with the Bar Council? The JAG Legal Branch is the PAF's law commission for legal advisers and courts martial.",
  },
  {
    slug: "gd-pilot-supplementary",
    name: "GD Pilot Supplementary Course (SSC)",
    tagline: "CAE graduates ke liye supplementary flying commission.",
    description:
      "The GD Pilot Supplementary course is advertised for candidates who already hold a degree in Aviation Management, Aerospace Engineering or Avionics, giving them a route into the flying branch on a short service basis. Selection uses the academic test, ISSB and medical board, with flight training at the College of Aeronautical Engineering.",
    icon: "plane",
    level: "Officer",
    commission: "Short Service Commission",
    eligibility: [
      "Pakistani male citizens.",
      "Age 21 to 23 years as per the advertisement.",
      "BS in Aviation Management, or BE in Aerospace Engineering or Avionics, from the College of Aeronautical Engineering or an equivalent institution.",
      "Height 5 ft 4 in minimum; 6/6 eyesight and flying aptitude.",
      "Medically and physically fit.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "21 – 23 years",
    education:
      "BS in Aviation Management or BE in Aerospace Engineering / Avionics from the CAE or equivalent.",
    physical:
      "Height 5 ft 4 in minimum · 6/6 uncorrected vision · flying aptitude and medical fitness.",
    nationality: "Pakistan",
    notEligible: [
      "Candidates without a CAE degree in the listed disciplines.",
      "Anyone outside the 21 to 23 year window.",
      "Anyone who fails the Pilot Aptitude Test or medical board.",
    ],
    benefits: [
      "Short service flying commission into the PAF.",
      "Flight training at the College of Aeronautical Engineering.",
      "Pilot status with flying allowance.",
      "Rank of Flying Officer with military benefits and pension.",
    ],
    steps: [
      "Register online at joinpaf.gov.pk for the GD Pilot Supplementary course.",
      "Clear the initial written test.",
      "Pass the preliminary medical and physical screening.",
      "Clear the ISSB assessment.",
      "Final medical board and selection.",
      "Complete flight training and receive commission as a Flying Officer.",
    ],
    duration: "Flight training at the College of Aeronautical Engineering",
    fee: "Free (government-funded)",
    documents: [
      "CNIC / B-Form and NADRA smart cards",
      "CAE degree transcript and DMC",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaf.gov.pk",
    summary:
      "Already a CAE graduate in aviation, aerospace or avionics, aged 21 to 23? The supplementary course is the direct route to the flying branch.",
  },
  {
    slug: "woman-officer-cadet",
    name: "Woman Officer Cadet (WOC)",
    tagline: "PAF ki female officer entry: Education, Admin, Accounts, Equipment, Medical, Dental.",
    description:
      "The Woman Officer Cadet programme is the PAF's commissioning route for women. Cadets are commissioned into branches such as Education, Administration, Accounts, Equipment, Medical and Dental, serving at PAF shore establishments, schools and hospitals, and they clear the same ISSB standard as male officer candidates.",
    icon: "users",
    level: "Officer",
    commission: "Regular Commission",
    eligibility: [
      "Pakistani female citizens.",
      "Age generally 17 to 24 years, depending on the branch and advertisement.",
      "FSc or graduation, or equivalent A-Level, in the branch's required discipline; MBBS or BDS for Medical and Dental branches.",
      "Height and physical standards as per PAF female candidates' norms.",
      "Medically and physically fit.",
    ],
    gender: "For female candidates",
    audience: "female",
    ageLimit: "17 – 24 years",
    education:
      "FSc, graduation, MBBS or BDS in the discipline required by the branch applied for.",
    physical:
      "Height as per female standard · medically fit · physical efficiency test as per PAF norms.",
    nationality: "Pakistan",
    notEligible: [
      "Male candidates; this programme is for women.",
      "Anyone outside the advertised age window for the branch.",
      "Anyone failing the medical board or ISSB assessment.",
    ],
    benefits: [
      "Commissioned officer rank in the Pakistan Air Force for women.",
      "Branches with strong professional demand: education, medical, dental, accounts and administration.",
      "Four-year funded training and a life-long military career.",
      "Officer pay, allowances, housing, medical care and pension.",
    ],
    steps: [
      "Watch joinpaf.gov.pk for the WOC advertisement and the branches open to women.",
      "Register online and select your branch.",
      "Clear the initial written and academic test.",
      "Pass the preliminary medical and physical screening.",
      "Clear the ISSB assessment and final interview.",
      "Complete training and receive commission.",
    ],
    duration: "Four years of cadet training",
    fee: "Free (fully government-funded)",
    documents: [
      "CNIC / B-Form and NADRA smart cards",
      "Matric, FSc / A-Level and degree certificates with DMC",
      "Medical or dental registration for Medical and Dental branches",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaf.gov.pk",
    summary:
      "Female candidate aged roughly 17 to 24? WOC is the PAF's female officer entry, with branches advertised per intake.",
  },
  {
    slug: "airman-technician",
    name: "Airman Technician (AT)",
    tagline: "Aircraft maintenance aur technical trades ka enlisted route.",
    description:
      "Airman Technicians are the technical backbone of the PAF. Recruited from FSc candidates with Physics and Mathematics, they train in aeronautical, electrical, instrument and armament trades at PAF technical training institutions and then maintain the fleet.",
    icon: "wrench",
    level: "Airman",
    commission: "Enlisted",
    eligibility: [
      "Pakistani citizens, male and female depending on the advertisement.",
      "Age 15 to 22 years as per the advertisement.",
      "FSc with Physics and Mathematics, or equivalent qualification.",
      "Height 5 ft 3 in minimum for airman technician categories.",
      "Medically and physically fit; physical fitness test applies.",
    ],
    gender: "Male and female candidates",
    audience: "both",
    ageLimit: "15 – 22 years",
    education: "FSc with Physics and Mathematics, or equivalent.",
    physical:
      "Height 5 ft 3 in minimum · run, push-ups and sit-ups · medical fitness.",
    nationality: "Pakistan",
    notEligible: [
      "Anyone without Physics and Mathematics at FSc level.",
      "Anyone outside the advertised age window.",
      "Anyone failing the physical fitness test or medical board.",
    ],
    benefits: [
      "Enlisted technical career on PAF aircraft and systems.",
      "Trade specialisation in aeronautical, electrical, instrument or armament.",
      "Free training, uniform, rations and medical care.",
      "Promotion through airman ranks to supervisory posts.",
    ],
    steps: [
      "Register online at joinpaf.gov.pk for the Airman Technician intake.",
      "Clear the initial written and academic test.",
      "Pass the physical fitness test.",
      "Pass the medical examination.",
      "Attend the interview and appear on the merit list.",
      "Report for technical training at a PAF technical training institution.",
    ],
    duration: "Technical training after initial selection",
    fee: "Free to apply",
    documents: [
      "CNIC / B-Form and NADRA smart cards",
      "Matric and FSc certificates with DMC",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaf.gov.pk",
    summary:
      "FSc with Physics and Maths, aged 15 to 22? Airman Technician is the enlisted technical route into the PAF.",
  },
  {
    slug: "airman-general-duty",
    name: "Airman General Duty (AGD)",
    tagline: "Security, fire service aur base operations ka enlisted route.",
    description:
      "Airman General Duty recruits enlisted personnel for security duties, fire service, ground handling and base operations. The entry requires Matric and is open to candidates who want to serve in the air force without an officer commission.",
    icon: "shield",
    level: "Airman",
    commission: "Enlisted",
    eligibility: [
      "Pakistani citizens, male and female depending on the advertisement.",
      "Age 15 to 22 years as per the advertisement.",
      "Matriculation with at least 45% marks.",
      "Height 5 ft 4 in minimum.",
      "Medically and physically fit; physical fitness test applies.",
    ],
    gender: "Male and female candidates",
    audience: "both",
    ageLimit: "15 – 22 years",
    education: "Matriculation with at least 45% marks.",
    physical:
      "Height 5 ft 4 in minimum · run, push-ups and sit-ups · medical fitness.",
    nationality: "Pakistan",
    notEligible: [
      "Anyone without Matric or below the required marks.",
      "Anyone outside the advertised age window.",
      "Anyone failing the physical fitness test or medical board.",
    ],
    benefits: [
      "Enlisted career in base security, fire service and ground operations.",
      "Free training, uniform, rations and medical care.",
      "Clear promotion through airman ranks.",
      "Government salary, allowances, housing and pension.",
    ],
    steps: [
      "Register online at joinpaf.gov.pk for the Airman General Duty intake.",
      "Clear the initial written test.",
      "Pass the physical fitness test.",
      "Pass the medical examination.",
      "Attend the interview and appear on the merit list.",
      "Report for basic airman training.",
    ],
    duration: "Basic airman training",
    fee: "Free to apply",
    documents: [
      "CNIC / B-Form and NADRA smart cards",
      "Matric certificate and DMC",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaf.gov.pk",
    summary:
      "Matric pass with 45% or more, aged 15 to 22? Airman General Duty is the enlisted route into PAF base operations.",
  },
];
