import type { Course } from "@/lib/content/types";

export const ARMY_COURSES: Course[] = [
  {
    slug: "pma-long-course",
    name: "PMA Long Course",
    tagline: "The intermediate route to a Regular Commission as an Army officer.",
    description:
      "The Pakistan Military Academy Long Course is the standard entry for intermediate holders who want a permanent commission in the Pakistan Army. Two years at PMA Kakul turn an FSc or FA pass into an officer, and every graduate leaves with a Regular Commission in a fighting or support corps.",
    icon: "graduation-cap",
    level: "Officer",
    commission: "Regular Commission",
    eligibility: [
      "Pakistani male citizens, including those of Northern Areas and Gilgit-Baltistan.",
      "Unmarried at the time of joining.",
      "Age 17 to 22 years on the cut-off date given in the advertisement.",
      "Passed FSc (Pre-Engineering / Pre-Medical) or FA, or O/A Levels with Physics and one other subject.",
      "Minimum height 5 ft 4 in (162.5 cm) with chest 30 in and 1.5 in expansion.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "17 – 22 years",
    education:
      "FSc (Pre-Engineering / Pre-Medical) or FA, or O/A Level with Physics plus Maths, Chemistry or Biology.",
    physical:
      "Height 5 ft 4 in minimum · chest 30 in with 1.5 in expansion · run, push-ups and general physical efficiency.",
    nationality: "Pakistan",
    notEligible: [
      "Married candidates.",
      "Anyone above the advertised age cut-off.",
      "Candidates below the minimum height or chest measurement.",
      "Anyone declared medically unfit by an Armed Forces hospital.",
    ],
    benefits: [
      "Regular Commission with a permanent career and pension.",
      "Two years of fully funded military, academic and physical training at PMA Kakul.",
      "Commission in Infantry, Armour, Artillery, Signals, Ordnance, Engineers, Education or Medical.",
      "Officer rank, entitled quarters, club facilities and children's education at government schools.",
    ],
    steps: [
      "Register online at joinpakarmy.gov.pk when the advertisement opens.",
      "Choose your test date and nearest Army Selection & Recruitment Centre (AS&RC).",
      "Clear the initial written test: verbal and non-verbal intelligence, English, Urdu, maths, Islamiyat, Pakistan studies and general knowledge.",
      "Pass the preliminary medical examination and the initial interview at the AS&RC.",
      "Clear the four-day ISSB assessment at Kohat, Malir or Gujranwala.",
      "Final medical board, then joining instructions to PMA Kakul.",
    ],
    duration: "2 years at PMA Kakul (after selection)",
    fee: "Free (fully government-funded)",
    documents: [
      "CNIC / B-Form and NADRA smart card",
      "Matric and FSc / O-Level certificates with DMC",
      "Domicile certificate",
      "Passport-size photographs",
      "Equivalence certificate for O/A-Level candidates",
    ],
    officialSite: "https://joinpakarmy.gov.pk",
    summary:
      "Aged 17 to 22, unmarried, with FSc or FA and at least 5 ft 4 in? You are on the primary PMA track. Always confirm the cut-off date in the live advertisement.",
  },
  {
    slug: "technical-cadet-course",
    name: "Technical Cadet Course (TCC)",
    tagline: "FSc Pre-Engineering se Corps of Engineers / Signals / EME mein officer commission.",
    description:
      "The Technical Cadet Course is the Army's engineering pipeline. Selected cadets are commissioned into technical corps such as the Corps of Engineers, Corps of Signals, Electrical and Mechanical Engineers and Ordnance, and they carry their academic specialisation with them into service.",
    icon: "wrench",
    level: "Officer",
    commission: "Regular Commission",
    eligibility: [
      "Pakistani male citizens, unmarried at the time of joining.",
      "Age 17 to 22 years as per the current advertisement.",
      "FSc Pre-Engineering with Physics, Chemistry and Mathematics, or equivalent A-Level combination.",
      "Minimum height 5 ft 4 in with the standard chest measurement.",
      "Medically and physically fit as per Army standards.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "17 – 22 years",
    education: "FSc Pre-Engineering (Physics, Chemistry, Mathematics) or equivalent A-Level.",
    physical:
      "Height 5 ft 4 in minimum · chest 30 in with 1.5 in expansion · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Candidates from Pre-Medical or arts combinations without the required maths and physics.",
      "Married candidates.",
      "Anyone failing the medical or physical efficiency test.",
    ],
    benefits: [
      "Regular Commission in a technical corps with a strong promotion track.",
      "Engineering specialisation that carries weight inside and outside the Army.",
      "Exposure to civil and military engineering projects, infrastructure and disaster response.",
      "Fully funded training with no tuition fee.",
    ],
    steps: [
      "Apply online at joinpakarmy.gov.pk in the advertised TCC window.",
      "Sit the initial written and academic test at the nearest AS&RC.",
      "Clear the preliminary medical examination and initial interview.",
      "Pass the ISSB psychological, GTO and interview assessment.",
      "Final medical board and joining to the technical cadet training.",
    ],
    duration: "2 years of cadet training, followed by branch attachment",
    fee: "Free (government-funded)",
    documents: [
      "CNIC / B-Form",
      "Matric and FSc Pre-Engineering certificates with DMC",
      "Domicile certificate",
      "Passport-size photographs",
    ],
    officialSite: "https://joinpakarmy.gov.pk",
    summary:
      "Pre-Engineering with Physics, Chemistry and Maths, aged 17 to 22? This is the course built for you. Check the exact subject combination in the advertisement.",
  },
  {
    slug: "graduate-course-ssc",
    name: "Graduate Course (SSC)",
    tagline: "Degree holders ke liye officer entry with a defined initial commission.",
    description:
      "The Graduate Course, commonly advertised as the Short Service Commission for graduates, takes a recognised degree holder and commissions them as an officer without the full PMA long-course route. It suits graduates who want a faster, structured path into the Army with a fixed initial period of service.",
    icon: "user-round",
    level: "Officer",
    commission: "Short Service Commission",
    eligibility: [
      "Pakistani male citizens.",
      "Age generally 22 to 26 years; the upper limit varies by corps and advertisement.",
      "Minimum graduation (BA / BSc / BS or equivalent) from an HEC-recognised institution.",
      "Height 5 ft 4 in minimum with the standard chest measurement.",
      "Medically and physically fit as per Army standards.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "22 – 26 years",
    education: "Graduation (BA / BSc / BS or equivalent) from a recognised university; final-year students may apply.",
    physical:
      "Height 5 ft 4 in minimum · chest 30 in with 1.5 in expansion · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Candidates below graduation or awaiting an intermediate result only.",
      "Anyone outside the advertised age window.",
      "Candidates who fail the medical or ISSB assessment.",
    ],
    benefits: [
      "Officer commission without repeating a full intermediate-based academy course.",
      "Graduate academic background respected within the corps.",
      "Defined initial commission with the possibility of extension or conversion on merit.",
      "Full officer privileges, pension and posting allowances.",
    ],
    steps: [
      "Register online at joinpakarmy.gov.pk during the advertised period.",
      "Clear the initial written test at the nearest AS&RC.",
      "Pass the preliminary medical examination and initial interview.",
      "Clear the four-day ISSB assessment.",
      "Final medical board and joining for officer training.",
    ],
    duration: "About 6 months of officer training, then corps attachment",
    fee: "Free (government-funded)",
    documents: [
      "CNIC / B-Form",
      "Matric, FSc and graduation transcripts with DMC",
      "Domicile certificate",
      "Passport-size photographs",
    ],
    officialSite: "https://joinpakarmy.gov.pk",
    summary:
      "Aged roughly 22 to 26 with a completed degree? You are the target graduate. Corps-wise age limits differ, so verify before you apply.",
  },
  {
    slug: "direct-short-service-commission",
    name: "Direct Short Service Commission (DSSC)",
    tagline: "Professionals ke liye corps-wise entry: education, IT, law, psychology, finance, veterinary.",
    description:
      "The Direct Short Service Commission recruits specialists straight into the Army's professional corps. Depending on the advertisement, seats are advertised in the Army Education Corps, Corps of Signals (IT), Ordnance, Judge Advocate General, Corps of Remount Veterinary and Farms, Financial Management and Psychology. Selected officers serve a fixed commission with the option of extension.",
    icon: "scale",
    level: "Officer",
    commission: "Direct Short Service",
    eligibility: [
      "Pakistani citizens. Most corps are advertised for males; a few professional streams also open to females.",
      "Age typically 20 to 28 years; the limit is set per discipline in each advertisement.",
      "Post-graduation in the advertised discipline, e.g. MA / MSc / MS in the relevant subject, LLB for law officers, M.Sc Psychology, MBA / MS Finance, DVM for veterinary officers.",
      "Height 5 ft 4 in minimum for men with the standard chest measurement.",
      "Medically and physically fit as per Army standards.",
    ],
    gender: "Male and female (discipline dependent)",
    audience: "both",
    ageLimit: "20 – 28 years (discipline dependent)",
    education:
      "Post-graduation in the advertised discipline, with a minimum of 16 years of education for most streams.",
    physical:
      "Height 5 ft 4 in minimum for male candidates · medically and physically fit per Army standards.",
    nationality: "Pakistan",
    notEligible: [
      "Candidates without a post-graduation qualification in the advertised discipline.",
      "Anyone above the discipline-specific age limit.",
      "Candidates who do not meet the physical or medical standards.",
    ],
    benefits: [
      "Officer rank for specialists without repeating academy training.",
      "Professional career recognition: teaching, law, IT, finance, psychology and veterinary work inside the Army.",
      "Fixed initial commission with extension, and in-service study opportunities.",
      "Officer status, pension and allowances from the start.",
    ],
    steps: [
      "Watch the advertisement on joinpakarmy.gov.pk for the specific corps advertised.",
      "Register online and select the corps matching your qualification.",
      "Clear the initial written test: intelligence plus academic subjects at the AS&RC.",
      "Pass the medical examination and the initial interview.",
      "Clear the ISSB assessment for officer suitability.",
      "Final medical board and joining instructions.",
    ],
    duration: "About 9 months of initial officer training",
    fee: "Free (government-funded)",
    documents: [
      "CNIC / B-Form",
      "Matric, FSc, graduation and post-graduation transcripts with DMC",
      "Domicile certificate",
      "Professional registration or licence where applicable (bar council, PVMC)",
      "Passport-size photographs",
    ],
    officialSite: "https://joinpakarmy.gov.pk",
    summary:
      "A post-graduate in teaching, law, IT, psychology, finance or veterinary science, roughly 20 to 28? Track the corps that advertises your discipline.",
  },
  {
    slug: "army-medical-cadet",
    name: "Army Medical Cadet Course",
    tagline: "FSc ke baad MBBS / BDS karke Army Medical Corps mein doctor-officer.",
    description:
      "The Army Medical Cadet Course is the route for students who clear FSc Pre-Medical, earn an MBBS or BDS and then apply to be commissioned as a medical officer in the Army Medical Corps. It is a long preparation track, and the medical board at the end is as strict as the academic one.",
    icon: "stethoscope",
    level: "Officer",
    commission: "Regular Commission",
    eligibility: [
      "Pakistani male citizens, unmarried at the time of joining.",
      "Age 17 to 21 years, measured against the date of commencement of the course.",
      "FSc Pre-Medical, then MBBS or BDS from a recognised medical college.",
      "Registered with the Pakistan Medical and Dental Council.",
      "Height 5 ft 4 in minimum; medically fit on military standards.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "17 – 21 years",
    education: "FSc Pre-Medical followed by MBBS or BDS from a PMDC-recognised college.",
    physical:
      "Height 5 ft 4 in minimum · chest 30 in with 1.5 in expansion · medical fitness on military standards.",
    nationality: "Pakistan",
    notEligible: [
      "Candidates who have not completed MBBS / BDS or are not PMDC registered.",
      "Married candidates.",
      "Anyone failing the final medical board.",
    ],
    benefits: [
      "Medical officer commission in the Army Medical Corps.",
      "Specialised military medical training on top of the MBBS.",
      "Postgraduate study opportunities in military medicine.",
      "Officer status with full military benefits and pension.",
    ],
    steps: [
      "Complete FSc Pre-Medical and get admitted to a recognised medical college.",
      "Earn MBBS / BDS and register with the Pakistan Medical and Dental Council.",
      "Apply at joinpakarmy.gov.pk when the Medical Cadet advertisement opens.",
      "Clear the initial written test and the preliminary medical board.",
      "Pass the ISSB assessment and the final interview.",
      "Final medical board and joining for medical officer training.",
    ],
    duration: "MBBS / BDS plus initial medical officer training",
    fee: "Free at the Army stage (MBBS / BDS costs apply at medical college)",
    documents: [
      "CNIC / B-Form",
      "FSc Pre-Medical certificate and DMC",
      "MBBS / BDS degree and PMDC registration",
      "Domicile certificate",
      "Passport-size photographs",
    ],
    officialSite: "https://joinpakarmy.gov.pk",
    summary:
      "Planning to become a doctor and then serve as an Army medical officer? Start with FSc Pre-Medical and keep the age window in mind throughout.",
  },
  {
    slug: "army-medical-corps",
    name: "Army Medical Corps (MBBS Doctors)",
    tagline: "MBBS / specialist doctors ke liye direct medical commission.",
    description:
      "Doctors with an MBBS, BDS or a specialist qualification apply directly to the Army Medical Corps through the professional commission route. The intake is small, competitive and age-limited, and it is advertised separately from the medical cadet course.",
    icon: "stethoscope",
    level: "Officer",
    commission: "Short Service Commission",
    eligibility: [
      "Pakistani citizens, male or female depending on the advertisement.",
      "MBBS or BDS from a PMDC-recognised institution, registered with the council.",
      "Specialist degrees (FCPS / MS / MD) are preferred for specialist commissions.",
      "Age generally 24 to 28 years for medical officers.",
      "Medically fit and cleared by an Armed Forces medical board.",
    ],
    gender: "Male and female (advertisement dependent)",
    audience: "both",
    ageLimit: "24 – 28 years",
    education: "MBBS / BDS with PMDC registration; specialist qualification for specialist commissions.",
    physical: "Medically fit on military standards; physical standards per advertisement.",
    nationality: "Pakistan",
    notEligible: [
      "Doctors not registered with the Pakistan Medical and Dental Council.",
      "Candidates above the advertised age limit.",
      "Anyone failing the Armed Forces medical board.",
    ],
    benefits: [
      "Direct medical officer commission without repeating academy training.",
      "Work in command hospitals, field medical units and military medical establishments.",
      "Specialist career path in military medicine and surgery.",
      "Officer pay, allowances, pension and free medical care for the family.",
    ],
    steps: [
      "Monitor joinpakarmy.gov.pk for the Army Medical Corps advertisement.",
      "Register online with your PMDC number and qualification details.",
      "Clear the initial written test and preliminary medical board.",
      "Pass the ISSB assessment and interview.",
      "Final medical board and grant of commission.",
    ],
    duration: "Short orientation course, then posting",
    fee: "Free (government service)",
    documents: [
      "CNIC / B-Form",
      "MBBS / BDS degree and PMDC registration certificate",
      "Specialist degree and council registration where applicable",
      "Domicile certificate",
      "Passport-size photographs",
    ],
    officialSite: "https://joinpakarmy.gov.pk",
    summary:
      "An MBBS holder with PMDC registration, roughly 24 to 28? Medical commissions are advertised periodically, so watch the portal closely.",
  },
  {
    slug: "armed-forces-nursing-services",
    name: "Armed Forces Nursing Services (AFNS)",
    tagline: "Female nursing officers: FSc Pre-Medical se BSN, phir commissioned nursing service.",
    description:
      "AFNS is the female nursing commission of the Pakistan Armed Forces. Candidates clear FSc Pre-Medical, complete a recognised nursing degree, and are commissioned into the Army, Navy or Air Force nursing service. This is one of the main routes for women to serve as uniformed officers.",
    icon: "heart-pulse",
    level: "Officer",
    commission: "Commissioned",
    eligibility: [
      "Pakistani female citizens.",
      "Age generally 17 to 25 years, depending on the advertisement.",
      "FSc Pre-Medical, followed by a recognised nursing degree (BSN / BSc Nursing).",
      "Registered with the Pakistan Nursing Council.",
      "Height and physical standards as per the force's advertised female norms.",
    ],
    gender: "For female candidates",
    audience: "female",
    ageLimit: "17 – 25 years",
    education: "FSc Pre-Medical plus a PMDC / PNC-recognised nursing degree.",
    physical:
      "Height as per female standard (commonly 5 ft 2 in) · medically fit · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Male candidates; this commission is for women.",
      "Candidates without a completed recognised nursing degree.",
      "Anyone who fails the medical or physical efficiency test.",
    ],
    benefits: [
      "Commissioned nursing officer status in the Armed Forces.",
      "Recognised nursing degree with military clinical exposure.",
      "Career path into nursing administration and senior military medical posts.",
      "Female-specific accommodation, medical care and pension benefits.",
    ],
    steps: [
      "Complete FSc Pre-Medical and a recognised nursing degree.",
      "Register with the Pakistan Nursing Council.",
      "Apply when the AFNS advertisement appears on the relevant force portal.",
      "Clear the initial written test and preliminary medical board.",
      "Pass the ISSB assessment and interview.",
      "Final medical board and joining for nursing officer training.",
    ],
    duration: "Nursing degree plus initial commissioned training",
    fee: "Free at the Armed Forces stage",
    documents: [
      "CNIC / B-Form",
      "FSc Pre-Medical certificate and DMC",
      "Nursing degree and Pakistan Nursing Council registration",
      "Domicile certificate",
      "Passport-size photographs",
    ],
    summary:
      "Female candidate with FSc Pre-Medical and a nursing degree, aged roughly 17 to 25? AFNS is the route to a nursing commission.",
  },
  {
    slug: "lady-cadet-course",
    name: "Lady Cadet Course (LCC)",
    tagline: "Pakistan Army ki female officer entry: FA / FSc se commissioned rank.",
    description:
      "The Lady Cadet Course is the Pakistan Army's route for women to become commissioned officers. Selected candidates are commissioned into the Army Medical Corps, the Education Corps or the Military Nursing Service, and the selection standard, including ISSB, is the same used for male officer candidates.",
    icon: "users",
    level: "Officer",
    commission: "Regular Commission",
    eligibility: [
      "Pakistani female citizens, unmarried at the time of joining.",
      "Age 17 to 23 years as per the current advertisement.",
      "FA, FSc or O/A Levels from a recognised board.",
      "Height and physical standards as per the Army's female candidates' norms.",
      "Medically and physically fit.",
    ],
    gender: "For female candidates",
    audience: "female",
    ageLimit: "17 – 23 years",
    education: "FA, FSc (Pre-Engineering / Pre-Medical) or O/A Levels.",
    physical:
      "Height as per female standard (commonly 5 ft 2 in) · physical efficiency test · medical fitness.",
    nationality: "Pakistan",
    notEligible: [
      "Male candidates; this course is for women.",
      "Married candidates at the time of joining.",
      "Anyone outside the advertised age window or failing the medical board.",
    ],
    benefits: [
      "Commissioned officer rank in the Army for women.",
      "Commission into Army Medical Corps, Education Corps or Military Nursing Service.",
      "Same ISSB standard and training pipeline as male officer candidates.",
      "Full officer benefits: pay, allowances, pension and family medical care.",
    ],
    steps: [
      "Register online at joinpakarmy.gov.pk when the LCC advertisement opens.",
      "Clear the initial written test at the nearest AS&RC.",
      "Pass the preliminary medical examination and initial interview.",
      "Clear the four-day ISSB assessment (female panel norms apply).",
      "Final medical board and joining for officer training at PMA Kakul.",
    ],
    duration: "2 years of cadet training at PMA Kakul",
    fee: "Free (government-funded)",
    documents: [
      "CNIC / B-Form",
      "Matric and FSc / O-Level certificates with DMC",
      "Domicile certificate",
      "Passport-size photographs",
    ],
    officialSite: "https://joinpakarmy.gov.pk",
    summary:
      "Female candidate, unmarried, aged 17 to 23 with FA or FSc? LCC is the Army's female officer entry. Confirm the age cut-off in the live advertisement.",
  },
  {
    slug: "soldier-joining",
    name: "Soldier (General Duty / Sipahi)",
    tagline: "Matric pass candidates ke liye direct enlistment in the Pakistan Army.",
    description:
      "Soldier recruitment, in Urdu Sipahi, is the most direct way into the Pakistan Army. Selected recruits clear a written test, physical standards and an interview, then go through basic military training before being allotted to a unit.",
    icon: "shield",
    level: "Soldier",
    commission: "Enlisted",
    eligibility: [
      "Pakistani male citizens.",
      "Age 17 and a half to 23 years.",
      "Matriculation (10th grade) or equivalent from a recognised board.",
      "Height at least 5 ft 4 in (162.5 cm); chest 30 in with 1.5 in expansion.",
      "Medically fit with no criminal record and of good character.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "17½ – 23 years",
    education: "Matriculation (10th grade) or equivalent; FSc is an advantage for trade postings.",
    physical:
      "Height 5 ft 4 in minimum · chest 30 in with 1.5 in expansion · 1.6 km run and physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Female candidates.",
      "Anyone under 17 and a half or over 23 years.",
      "Candidates below the height or chest minimum.",
      "Anyone with a criminal record or declared medically unfit.",
    ],
    benefits: [
      "A government career from early age with pension and post-service benefits.",
      "Free training, uniform, rations and medical care.",
      "Clear promotion path to Naib Khateeb and Non-Commissioned Officer ranks.",
      "Housing and schooling allowances for families.",
    ],
    steps: [
      "Register online at joinpakarmy.gov.pk or walk in to the nearest Recruitment & Selection Centre when registration opens.",
      "Clear the written test: maths, English, Urdu, Islamiyat, Pakistan studies and general knowledge.",
      "Pass the physical and medical examination.",
      "Attend the final interview and appear on the merit list.",
      "Report for basic military training and get allotted to a unit.",
    ],
    duration: "About 6 months of basic training, then unit posting",
    fee: "Free to apply (fully government-funded)",
    documents: [
      "CNIC / B-Form",
      "Matric certificate and DMC",
      "Domicile certificate",
      "Passport-size photographs",
    ],
    officialSite: "https://joinpakarmy.gov.pk",
    summary:
      "Matric pass, aged 17 and a half to 23, height at least 5 ft 4 in? You can apply. Check the height before you spend time on the test preparation.",
  },
  {
    slug: "soldier-technical-trades",
    name: "Soldier (Technical & Clerical Trades)",
    tagline: "Clerk, store, technical, driver aur medical trades mein enlistment.",
    description:
      "Beyond General Duty, the Army recruits soldiers into specific trades: clerks, stores, technical assistants, drivers, tailors, cooks, medical assistants, veterinary assistants, physical trainers, musicians and more. Trade requirements differ, and some trades prefer FSc or technical certification.",
    icon: "package",
    level: "Soldier",
    commission: "Enlisted",
    eligibility: [
      "Pakistani male citizens.",
      "Age 17 and a half to 23 years for most trades.",
      "Matriculation as the base qualification; FSc or a technical certificate for specific trades.",
      "Trade-specific requirements, e.g. a driving licence for driver trades.",
      "Height 5 ft 4 in minimum with the standard chest measurement.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "17½ – 23 years",
    education:
      "Matriculation minimum; FSc, DAE or a trade certificate for technical trades.",
    physical:
      "Height 5 ft 4 in minimum · chest 30 in with 1.5 in expansion · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Female candidates.",
      "Candidates without the specific qualification or certificate for the trade applied for.",
      "Anyone failing the medical or physical standards.",
    ],
    benefits: [
      "Enlistment into a specific trade rather than a generic infantry posting.",
      "Trade skills that can later be certificated or used after service.",
      "Free training, uniform, rations and medical care.",
      "Promotion to Naib Khateeb and Non-Commissioned Officer ranks.",
    ],
    steps: [
      "Check which trades are open in the current advertisement at joinpakarmy.gov.pk.",
      "Register online and select your trade.",
      "Clear the written test for the advertised trade.",
      "Pass the physical, medical and driving (where required) tests.",
      "Attend the interview and appear on the merit list.",
      "Report for basic training and trade training.",
    ],
    duration: "About 6 months basic training plus trade training",
    fee: "Free to apply",
    documents: [
      "CNIC / B-Form",
      "Matric certificate and DMC, plus FSc for trades that require it",
      "Trade certificate or driving licence where applicable",
      "Domicile certificate",
      "Passport-size photographs",
    ],
    officialSite: "https://joinpakarmy.gov.pk",
    summary:
      "Aged 17 and a half to 23 with Matric? Check which trades are open in the current advertisement, then prepare for that trade's specific test.",
  },
  {
    slug: "junior-commissioned-officer",
    name: "Junior Commissioned Officer (Naib Khateeb)",
    tagline: "Dars-e-Nizami pass candidates ke liye JCO rank.",
    description:
      "The Junior Commissioned Officer entry, commonly called Naib Khateeb, recruits candidates who have passed the Dars-e-Nizami from a recognised madrasa or equivalent institution. Selected candidates are commissioned as Junior Commissioned Officers, a rank above the ordinary soldier.",
    icon: "compass",
    level: "Soldier",
    commission: "Commissioned",
    eligibility: [
      "Pakistani male citizens.",
      "Pass in Dars-e-Nizami from a recognised Islamic institution.",
      "Age generally 21 to 28 years, as per the advertisement.",
      "Height 5 ft 4 in minimum with the standard chest measurement.",
      "Medically and physically fit.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "21 – 28 years",
    education: "Dars-e-Nizami pass certificate from a recognised institution.",
    physical:
      "Height 5 ft 4 in minimum · chest 30 in with 1.5 in expansion · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Female candidates.",
      "Anyone without a recognised Dars-e-Nizami pass certificate.",
      "Candidates outside the advertised age window.",
    ],
    benefits: [
      "Junior Commissioned Officer rank from the start.",
      "Direct supervisory responsibility over soldiers.",
      "Promotion route to Naib Subedar and Subedar.",
      "Government salary, allowances, pension and family benefits.",
    ],
    steps: [
      "Watch the JCO advertisement on joinpakarmy.gov.pk.",
      "Register online with your Dars-e-Nizami certificate details.",
      "Clear the initial written test at the nearest AS&RC.",
      "Pass the physical and medical examination.",
      "Attend the interview and appear on the merit list.",
      "Report for JCO training.",
    ],
    duration: "About 6 to 9 months of training",
    fee: "Free to apply",
    documents: [
      "CNIC / B-Form",
      "Matric certificate and DMC",
      "Dars-e-Nizami certificate from a recognised institution",
      "Domicile certificate",
      "Passport-size photographs",
    ],
    officialSite: "https://joinpakarmy.gov.pk",
    summary:
      "Dars-e-Nizami pass, aged roughly 21 to 28? This entry gives you JCO rank instead of starting as an ordinary soldier.",
  },
  {
    slug: "lowar-officers",
    name: "Lowar Officers (LOV)",
    tagline: "Gilgit-Baltistan aur Azad Kashmir ke candidates ke liye officer entry.",
    description:
      "The Lowar Officers course is an Army officer entry created for candidates from Gilgit-Baltistan, Azad Jammu and Kashmir and the Northern Areas. It follows an intermediate-based selection route and commissions officers who are later posted across the Army and in northern areas.",
    icon: "mountain",
    level: "Officer",
    commission: "Regular Commission",
    eligibility: [
      "Citizens of Gilgit-Baltistan, Azad Jammu and Kashmir, or the Northern Areas.",
      "Male candidates, unmarried at the time of joining.",
      "Age 17 to 22 years as per the advertisement.",
      "FSc or FA, or O/A Levels, from a recognised board.",
      "Height 5 ft 4 in minimum with the standard chest measurement.",
    ],
    gender: "For male candidates (Gilgit-Baltistan / AJK / Northern Areas)",
    audience: "male",
    ageLimit: "17 – 22 years",
    education: "FSc or FA, or O/A Levels, from a recognised board.",
    physical:
      "Height 5 ft 4 in minimum · chest 30 in with 1.5 in expansion · physical efficiency test.",
    nationality: "Pakistan (Gilgit-Baltistan / AJK / Northern Areas)",
    notEligible: [
      "Candidates domiciled outside Gilgit-Baltistan, AJK and the Northern Areas.",
      "Married candidates.",
      "Anyone failing the medical or ISSB assessment.",
    ],
    benefits: [
      "Officer commission for candidates from the northern areas.",
      "Reserved-intake route with dedicated seats for the region.",
      "Full officer career, pension and military benefits.",
      "Fully funded training with no tuition fee.",
    ],
    steps: [
      "Watch the Lowar Officers advertisement on joinpakarmy.gov.pk.",
      "Register online with your domicile and qualification details.",
      "Clear the initial written test at the nearest AS&RC.",
      "Pass the preliminary medical board and the initial interview.",
      "Clear the ISSB assessment.",
      "Final medical board and joining for officer training.",
    ],
    duration: "2 years of cadet training",
    fee: "Free (government-funded)",
    documents: [
      "CNIC / B-Form",
      "Domicile certificate from Gilgit-Baltistan / AJK / Northern Areas",
      "Matric and FSc certificates with DMC",
      "Passport-size photographs",
    ],
    officialSite: "https://joinpakarmy.gov.pk",
    summary:
      "Domicile of Gilgit-Baltistan, AJK or the Northern Areas, aged 17 to 22 with FSc? This is your dedicated officer entry route.",
  },
];
