import type { Course } from "@/lib/content/types";

export const NAVY_COURSES: Course[] = [
  {
    slug: "pn-cadet",
    name: "PN Cadet (Operations Branch)",
    tagline: "The permanent-commission cadet route into the Pakistan Navy's operations branch.",
    description:
      "PN Cadet (Operations) is the core cadet entry into the Pakistan Navy. Selected cadets train at the Pakistan Naval Academy and are commissioned into the Operations branch, which handles navigation, communication, electronics, submarines and surface watchkeeping.",
    icon: "compass",
    level: "Officer",
    commission: "Regular Commission",
    eligibility: [
      "Pakistani male citizens; civilian candidates must be unmarried.",
      "Age 16 and a half to 21 years for civilians; 17 to 23 years for serving Armed Forces personnel in uniform.",
      "Matric plus FSc or O/A Levels with at least 60% marks in Physics, Mathematics and Chemistry, or Physics, Mathematics and Computer Science, or Physics, Mathematics and Statistics.",
      "Minimum height 5 ft 4 in.",
      "Medically and physically fit for sea service.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "16½ – 21 years",
    education:
      "FSc or O/A Level with at least 60% marks in Physics, Mathematics with Chemistry / Computer Science / Statistics.",
    physical:
      "Height 5 ft 4 in minimum · good medical standard and eyesight · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Married civilian candidates.",
      "Anyone outside the 16 and a half to 21 year window for civilians.",
      "Candidates below 60% marks or without the required subject combination.",
      "Anyone declared medically unfit for sea service.",
    ],
    benefits: [
      "Permanent Commission as a Sub-Lieutenant in the Operations branch.",
      "Fully funded training at the Pakistan Naval Academy.",
      "A degree in Maritime Sciences plus further specialisation tracks.",
      "Sea service, foreign postings and a clear career ladder to command.",
    ],
    steps: [
      "Register online at joinpaknavy.gov.pk and pick your initial test date and Navy Recruitment & Selection Centre.",
      "Clear the computer-based initial test: intelligence and academic portions.",
      "Pass the preliminary medical examination and the initial interview.",
      "Clear the Physical Efficiency Test (PET).",
      "Clear the four-day ISSB assessment with naval screening.",
      "Final medical examination and selection by Naval Headquarters on merit.",
    ],
    duration: "4 years of basic training at the Pakistan Naval Academy",
    fee: "Free (fully government-funded)",
    documents: [
      "CNIC / B-Form",
      "Matric and FSc / O-Level certificates with DMC",
      "IBCC equivalence certificate for O/A-Level candidates",
      "Hope certificate from the college head for FSc appearing candidates",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaknavy.gov.pk",
    summary:
      "Aged 16 and a half to 21, unmarried, with 60% in FSc Physics, Maths and Chemistry? This is the main Navy cadet route. Term and dates change with every advertisement.",
  },
  {
    slug: "pn-cadet-supply",
    name: "PN Cadet (Supply Branch)",
    tagline: "Logistics, supply chain and management ka permanent commission route.",
    description:
      "The PN Cadet Supply Branch commissions officers into naval logistics: warehousing, supply chain, procurement, inventory and finance support at sea and ashore. Cadets earn a degree in Supply Chain Management as part of the four-year programme.",
    icon: "package",
    level: "Officer",
    commission: "Regular Commission",
    eligibility: [
      "Pakistani male citizens; civilian candidates must be unmarried.",
      "Age 16 and a half to 21 years for civilians.",
      "Matric plus FSc or O/A Levels with at least 60% marks in an eligible subject combination.",
      "Minimum height 5 ft 4 in.",
      "Medically and physically fit for naval service.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "16½ – 21 years",
    education: "FSc or O/A Level with at least 60% marks in the advertised subject combinations.",
    physical:
      "Height 5 ft 4 in minimum · medical fitness and eyesight standards · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Married civilian candidates.",
      "Candidates outside the advertised age window or below 60% marks.",
      "Anyone failing the medical board or physical efficiency test.",
    ],
    benefits: [
      "Permanent Commission in the Supply branch of the Pakistan Navy.",
      "Four years of funded training with a BS in Supply Chain Management.",
      "Logistics career across naval bases, dockyards and fleet support.",
      "Progression to supply, procurement and command appointments.",
    ],
    steps: [
      "Register online at joinpaknavy.gov.pk for the Supply branch.",
      "Clear the computer-based initial test.",
      "Pass the preliminary medical examination and initial interview.",
      "Clear the PET, then the ISSB assessment.",
      "Final medical examination and merit-based selection.",
    ],
    duration: "4 years of basic training at the Pakistan Naval Academy",
    fee: "Free (fully government-funded)",
    documents: [
      "CNIC / B-Form",
      "Matric and FSc / O-Level certificates with DMC",
      "IBCC equivalence certificate for O/A-Level candidates",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaknavy.gov.pk",
    summary:
      "Aged 16 and a half to 21 with 60% in FSc? The Supply branch is a permanent-commission cadet route with a logistics degree attached.",
  },
  {
    slug: "pn-cadet-engineering",
    name: "PN Cadet (Engineering Branches)",
    tagline: "Marine, Weapon and Construction engineering cadets with a BE degree.",
    description:
      "Engineering PN Cadets train for the Navy's technical branches: Marine Engineering (BE Mechanical), Weapon Engineering (BE Electrical) and Construction / Naval Architecture. The four-year programme combines naval training with a full engineering degree from NUST.",
    icon: "wrench",
    level: "Officer",
    commission: "Regular Commission",
    eligibility: [
      "Pakistani male citizens; civilian candidates must be unmarried.",
      "Age 16 and a half to 21 years for civilians.",
      "FSc Pre-Engineering with Physics, Mathematics and Chemistry, or equivalent A-Level, with at least 60% marks.",
      "Minimum height 5 ft 4 in.",
      "Medically and physically fit for engineering service at sea.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "16½ – 21 years",
    education:
      "FSc Pre-Engineering (Physics, Mathematics, Chemistry) with at least 60% marks, or equivalent A-Level.",
    physical:
      "Height 5 ft 4 in minimum · medical and eyesight standards · physical efficiency test.",
    nationality: "Pakistan",
    notEligible: [
      "Married civilian candidates.",
      "Candidates from non-technical subject combinations.",
      "Anyone below the height or medical standards.",
    ],
    benefits: [
      "Permanent Commission in Marine, Weapon or Construction engineering.",
      "Four-year programme with a BE in Marine, Electrical or Naval Architecture.",
      "Hands-on fleet, dockyard and submarine support experience.",
      "Engineering qualifications recognised in the civilian sector too.",
    ],
    steps: [
      "Register online at joinpaknavy.gov.pk for the Engineering branch group.",
      "Clear the computer-based initial test.",
      "Pass the preliminary medical examination and the initial interview.",
      "Clear the PET and the ISSB assessment.",
      "Final medical examination and merit-based selection.",
    ],
    duration: "4 years of basic and academic training at the Naval Academy",
    fee: "Free (fully government-funded)",
    documents: [
      "CNIC / B-Form",
      "Matric and FSc Pre-Engineering certificates with DMC",
      "IBCC equivalence certificate for A-Level candidates",
      "Domicile certificate and passport-size photographs",
    ],
    officialSite: "https://joinpaknavy.gov.pk",
    summary:
      "FSc Pre-Engineering with Physics, Maths and Chemistry at 60% or above, aged 16 and a half to 21? The engineering cadet route is built for you.",
  },
  {
    slug: "short-service-naval",
    name: "Navy Short Service Commission (SSC)",
    tagline: "Graduates ke liye corps-wise entry: Supply, Medical, Education, Law, IT, Engineering.",
    description:
      "The Navy's Short Service Commission recruits graduates directly into professional and technical branches as and when vacancies are advertised. Branches typically include Supply, Medical, Education, Naval Law, Information Technology and Special Branch (computer programmers), and the commission is for a fixed period that can be extended.",
    icon: "anchor",
    level: "Officer",
    commission: "Short Service Commission",
    eligibility: [
      "Pakistani citizens; branches are advertised for male, female or both.",
      "Age typically 20 to 32 years, depending on the branch advertised.",
      "Graduation from an HEC-recognised university; post-graduation for Education, IT and Law branches.",
      "Height 5 ft 4 in minimum for male candidates.",
      "Medically and physically fit for naval duties.",
    ],
    gender: "Male and female (branch dependent)",
    audience: "both",
    ageLimit: "20 – 32 years (branch dependent)",
    education:
      "Graduation (or BE / MBBS / LLB / MA as advertised) from an HEC-recognised university.",
    physical:
      "Height 5 ft 4 in minimum for male candidates · medically fit · good eyesight for seagoing roles.",
    nationality: "Pakistan",
    notEligible: [
      "Candidates without the qualification advertised for their chosen branch.",
      "Anyone above the branch-specific age limit.",
      "Anyone failing the naval medical standard.",
    ],
    benefits: [
      "Commissioned officer rank without the full cadet pathway.",
      "Specialised career in supply, medical, education, law, IT or engineering.",
      "Salary and allowances from the day of commissioning.",
      "Fixed initial commission with the option of extension or conversion on merit.",
    ],
    steps: [
      "Watch joinpaknavy.gov.pk for the SSC advertisement and its branch list.",
      "Register online and select your branch.",
      "Clear the initial written and academic assessment.",
      "Pass the medical and physical screening.",
      "Clear the naval interview and selection board.",
      "Complete about nine months of training at naval establishments.",
    ],
    duration: "About 9 months of branch and professional training",
    fee: "Free (government-funded)",
    documents: [
      "CNIC / B-Form",
      "Graduation / post-graduation transcripts with DMC",
      "Professional registration where required (medical, bar council)",
      "Domicile certificate",
      "Passport-size photographs",
    ],
    officialSite: "https://joinpaknavy.gov.pk",
    summary:
      "Aged 20 to 32 with a degree? Navy SSC is advertised branch by branch. Check whether your branch is open to male, female or both candidates.",
  },
  {
    slug: "navy-ssc-women",
    name: "Navy Short Service Commission (Women)",
    tagline: "Female officers ki entry: Supply, Education, Medical aur Legal branches.",
    description:
      "Women can be commissioned in the Pakistan Navy through the Short Service Commission for Women, generally in Supply, Education, Medical and Legal branches. Selection follows the naval process of written test, medical board, physical efficiency test and interview, with female candidates assessed against female physical standards.",
    icon: "users",
    level: "Officer",
    commission: "Short Service Commission",
    eligibility: [
      "Pakistani female citizens.",
      "Age generally 18 to 30 years, depending on the branch and advertisement.",
      "Graduation from an HEC-recognised university; post-graduation for Education and Law.",
      "Height and physical standards as per the Navy's female candidates' norms.",
      "Medically and physically fit for naval service.",
    ],
    gender: "For female candidates",
    audience: "female",
    ageLimit: "18 – 30 years",
    education: "Graduation or post-graduation in the discipline advertised for the branch.",
    physical:
      "Height as per female standard · medically fit · physical efficiency test as per naval norms.",
    nationality: "Pakistan",
    notEligible: [
      "Male candidates; this commission is for women.",
      "Anyone outside the advertised age window for her branch.",
      "Anyone failing the naval medical board or physical efficiency test.",
    ],
    benefits: [
      "Commissioned officer rank in the Pakistan Navy for women.",
      "Branches with strong civilian demand: supply, education, medical and legal.",
      "Fixed commission with extension, plus allowances and pension.",
      "Female accommodation and medical facilities at naval establishments.",
    ],
    steps: [
      "Watch joinpaknavy.gov.pk for the women's SSC advertisement.",
      "Register online and select the branch open to women.",
      "Clear the initial written and academic test.",
      "Pass the medical and physical screening.",
      "Attend the naval interview and selection board.",
      "Complete the professional training at a naval establishment.",
    ],
    duration: "About 9 months of training",
    fee: "Free (government-funded)",
    documents: [
      "CNIC / B-Form",
      "Graduation / post-graduation transcripts with DMC",
      "Domicile certificate",
      "Passport-size photographs",
    ],
    officialSite: "https://joinpaknavy.gov.pk",
    summary:
      "Female graduate, aged roughly 18 to 30? Navy women SSC is advertised periodically for supply, education, medical and legal branches.",
  },
  {
    slug: "pn-cadet-medical",
    name: "PN Cadet (Medical)",
    tagline: "MBBS doctors ke liye Navy Medical Branch commission.",
    description:
      "The Navy commissions medical officers through the PN Cadet medical route and through professional Short Service Commission advertisements. Doctors serve in naval hospitals, fleet medical units and the Marine Academy, with naval medical training on top of their MBBS.",
    icon: "stethoscope",
    level: "Officer",
    commission: "Regular Commission",
    eligibility: [
      "Pakistani citizens, male or female depending on the advertisement.",
      "MBBS from a PMDC-recognised medical college, registered with the Pakistan Medical and Dental Council.",
      "Age generally 22 to 30 years, as advertised.",
      "Height 5 ft 4 in minimum for male candidates.",
      "Medically and physically fit on military standards.",
    ],
    gender: "Male and female (advertisement dependent)",
    audience: "both",
    ageLimit: "22 – 30 years",
    education: "MBBS with PMDC registration; specialist degrees preferred for specialist commissions.",
    physical:
      "Height 5 ft 4 in minimum for male candidates · medically fit on military standards.",
    nationality: "Pakistan",
    notEligible: [
      "Doctors not registered with the Pakistan Medical and Dental Council.",
      "Anyone above the advertised age limit.",
      "Anyone failing the Armed Forces medical board.",
    ],
    benefits: [
      "Medical officer commission in the Pakistan Navy.",
      "Naval medical practice: hospitals, fleet units and shore establishments.",
      "Postgraduate study and specialisation support.",
      "Officer pay, allowances, pension and family medical care.",
    ],
    steps: [
      "Monitor joinpaknavy.gov.pk for the medical commission advertisement.",
      "Register online with PMDC details.",
      "Clear the initial written test and preliminary medical board.",
      "Pass the interview and selection board.",
      "Final medical board and joining for medical officer training.",
    ],
    duration: "Initial medical orientation course, then posting",
    fee: "Free (government service)",
    documents: [
      "CNIC / B-Form",
      "MBBS degree and PMDC registration certificate",
      "Domicile certificate",
      "Passport-size photographs",
    ],
    officialSite: "https://joinpaknavy.gov.pk",
    summary:
      "MBBS with PMDC registration? Naval medical commissions appear in specific advertisements. Watch the Navy portal and check whether the intake is open to women.",
  },
  {
    slug: "navy-ratings",
    name: "Navy Ratings (Enlisted)",
    tagline: "Able Seaman, Leading Seaman, Ordinary Seaman aur marine technicians.",
    description:
      "Below officer rank, the Pakistan Navy recruits Ratings: Ordinary Seaman, Leading Seaman, Able Seaman and marine engineering technicians. Ratings serve on ships and shore establishments, and the promotion ladder runs from Ordinary Seaman up to Chief Petty Officer.",
    icon: "ship",
    level: "Rating",
    commission: "Enlisted",
    eligibility: [
      "Pakistani male citizens; some ratings are also advertised for females.",
      "Age generally 18 to 25 years, as per the advertisement.",
      "Matriculation minimum; FSc required for marine technician trades.",
      "Height 5 ft 4 in minimum for male candidates.",
      "Medically fit for sea service and of good character.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "18 – 25 years",
    education: "Matriculation minimum; FSc for marine engineering technician trades.",
    physical:
      "Height 5 ft 4 in minimum · swimming and physical efficiency tests · medical fitness for sea service.",
    nationality: "Pakistan",
    notEligible: [
      "Anyone unable to meet the swimming and physical standards for sea service.",
      "Candidates outside the advertised age window.",
      "Anyone medically unfit for service at sea.",
    ],
    benefits: [
      "Enlisted naval service with a clear promotion path to Chief Petty Officer.",
      "Sea service, watches and travel that most enlistees never get otherwise.",
      "Free training, rations, uniform and medical care.",
      "Re-enlistment and trade specialisation options.",
    ],
    steps: [
      "Watch joinpaknavy.gov.pk and local Navy units for rating advertisements.",
      "Register or apply at the nearest Navy Recruitment & Selection Centre.",
      "Clear the written test for the advertised rating.",
      "Pass the swimming, physical and medical tests.",
      "Attend the interview and clear the selection board.",
      "Report for basic and rating training.",
    ],
    duration: "Basic training followed by rating training",
    fee: "Free to apply",
    documents: [
      "CNIC / B-Form",
      "Matric certificate and DMC, plus FSc for technician trades",
      "Domicile certificate",
      "Passport-size photographs",
    ],
    officialSite: "https://joinpaknavy.gov.pk",
    summary:
      "Aged 18 to 25 and comfortable in the water? Ratings are the enlisted route into the Navy, and swimming ability is often the first cut.",
  },
  {
    slug: "merchant-navy-cadet",
    name: "Merchant Navy Cadet (Pakistan Marine Academy)",
    tagline: "Deck aur Marine Engineering cadets: 2 saal residential training, merchant ships.",
    description:
      "The Pakistan Marine Academy trains nautical deck and marine engineering cadets for the merchant navy. The two-year residential programme awards an associate degree in Nautical Science and Marine Engineering along with IMO pre-sea mandatory certificates, after which cadets serve on merchant vessels.",
    icon: "ship",
    level: "Cadet",
    commission: "Cadet",
    eligibility: [
      "Unmarried male citizens of Pakistan.",
      "Age not more than 20 years; up to 21 years for candidates from FATA / Gilgit-Baltistan, AJK and Balochistan (one-year relaxation).",
      "FSc Pre-Engineering or A-Level with Physics, Chemistry and Mathematics, at least 55% marks; 60% in Part-I for Part-II appearing candidates with a hope certificate.",
      "Swimming ability and physical efficiency test.",
      "Colour-blind candidates are not eligible.",
    ],
    gender: "For male candidates",
    audience: "male",
    ageLimit: "Up to 20 years (21 for specified regions)",
    education: "FSc Pre-Engineering or A-Level (Physics, Chemistry, Mathematics) with at least 55% marks.",
    physical:
      "Swimming proficiency · 1.6 km run in 8 minutes · 15 push-ups, 15 sit-ups, 2 chin-ups in 2 minutes each.",
    nationality: "Pakistan",
    notEligible: [
      "Married candidates.",
      "Colour-blind candidates.",
      "Anyone without the required FSc or A-Level subject combination.",
      "Candidates who fail the entrance test, PET or medical examination.",
    ],
    benefits: [
      "Two-year residential marine training with a recognised associate degree.",
      "IMO pre-sea mandatory certificates and watchkeeping eligibility.",
      "Merchant navy career with international voyages and foreign earnings.",
      "Clear route from cadet to shipping officer ranks.",
    ],
    steps: [
      "Download the prospectus and application from marineacademy.edu.pk.",
      "Submit the application with the required pay order at the admission office or by courier.",
      "Sit the entrance test at the designated testing centre (minimum 50% to qualify).",
      "Pass the medical examination and the physical efficiency test.",
      "Attend the final interview; selection is on merit.",
      "Report for the two-year residential training at the Pakistan Marine Academy, Karachi.",
    ],
    duration: "2 years residential training at the Pakistan Marine Academy, Karachi",
    fee: "Course fee payable; need-based scholarships are also offered",
    documents: [
      "Matric and FSc / A-Level certificates with DMC",
      "Equivalence certificate for O/A-Level candidates",
      "CNIC / B-Form and domicile certificate",
      "Passport-size photographs",
      "Pay order / bank draft for the application fee",
    ],
    officialSite: "https://marineacademy.edu.pk",
    summary:
      "Unmarried, 20 or under, with FSc Pre-Engineering and swimming ability? The Marine Academy route takes you onto merchant ships in two years.",
  },
];
